scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      type: laser_filters/LaserArrayFilter
      name: median
      params:
        range_filter_chain:
          filter1:
            name: median
            type: filters/MultiChannelMedianFilterFloat
            params:
              number_of_observations: 5
              unused: 20
        intensity_filter_chain:
          filter1:
            name: median
            type: filters/MultiChannelMedianFilterFloat
            params:
              number_of_observations: 5
              unused: 20
    filter2:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: laser
        max_x: 0.4
        max_y: 1.3
        max_z: 0.4
        min_x: -1.2
        min_y: -1.3
        min_z: -0.4

        invert: False # activate to remove all points outside of the box
